# Production profile configuration
app:
  name: "Spring Boot Core Config Demo (PROD)"
  environment: "production"
  max-connections: 100
  debug-enabled: false
  allowed-origins:
    - "https://myapp.com"
    - "https://api.myapp.com"

# Minimal logging for production
logging:
  level:
    root: WARN
    com.acu.coreconfig: INFO
    org.springframework.web: WARN
    org.springframework.boot.autoconfigure: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/core-config-prod.log
    max-size: 100MB
    max-history: 30

# Secure actuator configuration for production
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: never
    configprops:
      show-values: never
    env:
      show-values: never

# Server configuration for production
server:
  port: 8080
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
