# Spring Boot Quick Start Application Configuration

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Application Information
spring:
  application:
    name: 01-quick-start
  
  # Logging Configuration
  output:
    ansi:
      enabled: always

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Logging Configuration
logging:
  level:
    com.acu.quickstart: DEBUG
    org.springframework.boot.actuate: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
