# Development Profile Configuration

# Enhanced logging for development
logging:
  level:
    com.acu.quickstart: DEBUG
    org.springframework.boot.actuate: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Expose all actuator endpoints in development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always

# Development-specific server settings
server:
  error:
    include-message: always
    include-binding-errors: always
