# Production profile configuration
spring:
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:yourUser}
    password: ${DB_PASSWORD:changeit}
  
  # JPA Configuration for PostgreSQL
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    defer-datasource-initialization: false

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

# Logging for production
logging:
  level:
    com.acu.datajpa: INFO
    org.springframework.data.jpa: WARN
    org.hibernate.SQL: WARN
