# Main application configuration for Day 5: Data JPA and Database Integration
spring:
  application:
    name: data-jpa-demo
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate  # Use validate for production, create-drop for development
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect  # Will be overridden by profiles
    defer-datasource-initialization: false

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true

# Server configuration
server:
  port: 8080

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

# Logging configuration
logging:
  level:
    root: INFO
    com.acu.datajpa: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
