apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-app
  namespace: kube-app-ns
  labels:
    app: kube-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-app
  template:
    metadata:
      labels:
        app: kube-app
    spec:
      containers:
      - name: kube-app
        image: vuhunghn/kube:0.0.8-optimized
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: kube-app-config
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kube
  name: kube
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube
  type: ClusterIP
status:
  loadBalancer: {}
