apiVersion: v1
kind: Service
metadata:
  name: kube-app-service
  namespace: kube-app-ns
  labels:
    app: kube-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: kube-app
