server:
  port: 8086

spring:
  application:
    name: kafka-spring-demo
  
  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: message-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.acu.kafka.model
        spring.json.type.mapping: message:com.acu.kafka.model.Message
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.acu.kafka.model.Message
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

logging:
  level:
    com.acu.kafka: DEBUG
    org.springframework.kafka: INFO
